// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb0OQdZExFXKMQkn2ev-S9ULbRk4NvVu4',
    appId: '1:984196952891:web:f93cb54fb7587c4e6cbd1e',
    messagingSenderId: '984196952891',
    projectId: 'e-commerce-374b0',
    authDomain: 'e-commerce-374b0.firebaseapp.com',
    storageBucket: 'e-commerce-374b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhICQUSq1kNCpp8ctWEMnrznlHK33bnw',
    appId: '1:984196952891:android:f54b3c20b45b50f06cbd1e',
    messagingSenderId: '984196952891',
    projectId: 'e-commerce-374b0',
    storageBucket: 'e-commerce-374b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpTtGEE6k9qIylpXt6kw5DorO0ACSyzc',
    appId: '1:984196952891:ios:2375d145e72e84fb6cbd1e',
    messagingSenderId: '984196952891',
    projectId: 'e-commerce-374b0',
    storageBucket: 'e-commerce-374b0.appspot.com',
    iosClientId: '984196952891-gmnruk3pqni6neim3b4ki71b842q49hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStoreApp',
  );
}
